INSERT  INTO USER (USER_id,EMAIL,PASSWORD)
VALUES(1,'Pallavi@yahoo.com','pqae2');
INSERT  INTO USER (USER_id,EMAIL,PASSWORD)
VALUES(2,'Twinkle@gmail.com','opiyt1');
INSERT  INTO USER (USER_id,EMAIL,PASSWORD)
VALUES(3,'Ashu1@hotmail.com','potyrq2');
INSERT  INTO  ROLE (ROLE_ID,RNAME,RCODE)
VALUES(123,'Manager',11);
INSERT  INTO  ROLE (ROLE_ID,RNAME,RCODE)
VALUES(124,'Ass.Manager',12);
INSERT  INTO  ORGANIZATION (ORG_ID,ORG_NAME,ORG_CODE)
VALUES(4,'Health',11);
INSERT  INTO  ORGANIZATION
VALUES(5,'SocialWelfare',13);