DROP TABLE IF EXISTS USER;
CREATE TABLE USER(
USER_ID INT NOT NULL,
EMAIL VARCHAR(40),
PASSWORD VARCHAR(20));
DROP TABLE IF EXISTS ROLE;
CREATE TABLE ROLE(
ROLE_ID INT NOT NULL,
RNAME VARCHAR(40),
RCODE INT(5));
DROP TABLE IF EXISTS ORGANIZATION;
CREATE TABLE ORGANIZATION(
ORG_ID INT(8),
ORG_NAME VARCHAR(20),
ORG_CODE INT(4));

